# Generated by Django 4.2.5 on 2023-11-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoUno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
