# Generated by Django 4.2.5 on 2023-11-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoUno', '0002_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En alquiler', 'En alquiler'), ('En proceso de entrega', 'En proceso de entrega'), ('Devuelto', 'Devuelto'), ('Perdido', 'Perdido'), ('Dañado', 'Dañado')], default='Disponible', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(default=123456789, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
    ]
