# Generated by Django 4.2.5 on 2023-11-09 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoUno', '0003_alquiler_estado_cliente_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='El número de teléfono debe tener exactamente 10 caracteres.'), django.core.validators.MaxLengthValidator(limit_value=10, message='El número de teléfono debe tener exactamente 10 caracteres.')]),
        ),
    ]
