# Generated by Django 4.2.5 on 2023-11-09 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoUno', '0004_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
