# Generated by Django 4.2.5 on 2023-11-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoUno', '0005_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
