# Generated by Django 4.2.5 on 2023-11-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoUno', '0006_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='correo_electronico',
            new_name='email',
        ),
    ]
