# Generated by Django 4.2.5 on 2023-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoUno', '0008_venta_alquiler_alter_juego_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
