# Generated by Django 4.2.5 on 2023-11-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoUno', '0010_cliente_juegos_alquilados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='juegos_alquilados',
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo_venta',
            field=models.CharField(default=212, max_length=20),
            preserve_default=False,
        ),
    ]
